name: Cache Flutter Dependencies

on:
  workflow_dispatch:  # Manually triggered

jobs:
  cache-flutter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Extract Flutter version from pubspec.yaml
        id: flutter-version
        run: |
          FLUTTER_VERSION=$(grep '^  flutter:' pubspec.yaml | sed 's/.*flutter: *//')
          if [ -z "$FLUTTER_VERSION" ]; then
            echo "Flutter version not found in pubspec.yaml"
            exit 1
          fi
          echo "FLUTTER_VERSION=$FLUTTER_VERSION" >> $GITHUB_ENV

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: "${{ env.FLUTTER_VERSION }}"

      - name: Cache Flutter dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
          key: ${{ runner.os }}-pub-cache-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-cache-

      - name: Install dependencies
        run: flutter pub get
