name: Cache Flutter Dependencies

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  cache-flutter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable  # You can change this to 'beta', 'master', etc.

      - name: Restore Flutter pub-cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
          key: ${{ runner.os }}-pub-cache-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-cache-

      - name: Install dependencies
        run: flutter pub get

      - name: Show cached packages
        run: ls ~/.pub-cache
