name: Build & Deploy Flutter Web & Apps

on:
  push:
    branches: [main]

jobs:
  setup-cache:
    runs-on: ubuntu-latest
    outputs:
      flutter-version: ${{ steps.extract.outputs.flutter-version }}
    steps:
      - uses: actions/checkout@v4

      - name: Extract Flutter version from pubspec.yaml
        id: extract
        run: |
          FLUTTER_VERSION=$(grep 'flutter:' pubspec.yaml | awk '{print $2}')
          echo "flutter-version=$FLUTTER_VERSION" >> "$GITHUB_OUTPUT"

      - name: Cache Flutter
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
            .dart_tool
            .packages
            build
          key: ${{ runner.os }}-flutter-${{ steps.extract.outputs.flutter-version }}
          restore-keys: |
            ${{ runner.os }}-flutter-

  build-web:
    needs: setup-cache
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ needs.setup-cache.outputs.flutter-version }}
      - run: flutter build web

  build-android:
    needs: setup-cache
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ needs.setup-cache.outputs.flutter-version }}
      - run: flutter build apk

  build-windows:
    needs: setup-cache
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ needs.setup-cache.outputs.flutter-version }}
      - run: flutter build windows

  build-linux:
    needs: setup-cache
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ needs.setup-cache.outputs.flutter-version }}
      - run: flutter build linux

  build-macos:
    needs: setup-cache
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ needs.setup-cache.outputs.flutter-version }}
      - run: flutter build macos
