name: Build & Deploy Flutter Web & Apps

on:
  workflow_dispatch:

jobs:
  build-web:
    name: Build & Deploy Flutter Web to gh-pages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Extract Flutter version from pubspec.yaml
        id: flutter-version
        run: |
          FLUTTER_VERSION=$(grep "flutter:" pubspec.yaml | awk '{print $2}')
          echo "FLUTTER_VERSION=$FLUTTER_VERSION" >> $GITHUB_ENV

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: "${{ env.FLUTTER_VERSION }}"

      - name: Enable Flutter web
        run: flutter config --enable-web

      - name: Get repository name
        id: repo-name
        run: echo "REPO_NAME=${GITHUB_REPOSITORY##*/}" >> $GITHUB_ENV

      - name: Install dependencies
        run: flutter pub get

      - name: Build Flutter Web
        run: flutter build web --release --base-href="/${{ env.REPO_NAME }}/"

      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web
          publish_branch: gh-pages
          force_orphan: true

  build-apps:
    name: Build Flutter Apps
    strategy:
      matrix:
        include:
          - platform: android
            os: ubuntu-latest
          - platform: linux
            os: ubuntu-latest
          - platform: windows
            os: windows-latest
          - platform: macos
            os: macos-latest
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Extract Flutter version from pubspec.yaml
        id: flutter-version
        shell: bash
        run: |
          FLUTTER_VERSION=$(grep "flutter:" pubspec.yaml | awk '{print $2}')
          echo "FLUTTER_VERSION=$FLUTTER_VERSION" >> $GITHUB_ENV

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: "${{ env.FLUTTER_VERSION }}"

      - name: Enable Flutter desktop support
        if: matrix.platform != 'android'
        run: flutter config --enable-${{ matrix.platform }}

      - name: Install dependencies
        run: flutter pub get

      - name: Build Flutter App
        run: |
          if [ "${{ matrix.platform }}" = "android" ]; then
            flutter build apk
          elif [ "${{ matrix.platform }}" = "linux" ]; then
            flutter build linux
          elif [ "${{ matrix.platform }}" = "windows" ]; then
            flutter build windows
          elif [ "${{ matrix.platform }}" = "macos" ]; then
            flutter build macos
          fi
